### ISSUE TITLE
Snapshot MatchOption Exclude

### ISSUE THREAD

**Issue by nscheibe** [SwissLife-OSS/snapshooter#114]
At the moment the snapshot match option "ignore" serializes the value of a field of a snapshot and just ignores this value during comparison. Now we should have the possibility to exclude a certain field completely. The excluded field shall not be serialized within the snapshot and of course shall not be compared.

Example:
Snapshot.Match(object, matchOptions => matchOptions.ExcludeField("<jsonPath>"))

**Comment by nscheibe** [comment]
Thx to @glucaci for the feature request

**Comment by relfman-cmg** [comment]
Bump. I would love this too. It will make diff'ing the mismatch less confusing. Maybe there's something that can be done on the serializer itself to not include it at all

**Comment by nscheibe** [comment]
I added it already with PR #163 

We will create a release tonight, then its in.

**Comment by nscheibe** [comment]
Version 0.10.0
