### ISSUE TITLE
Allow JsonSerializerSettings to be configurable

### ISSUE THREAD

**Issue by diogonborges** [SwissLife-OSS/snapshooter#115]
**Is your feature request related to a problem? Please describe.**
It should be possible to use other JsonSerializerSettings other than the hardcoded instance in the SnapshotSerializer

**Describe the solution you'd like**
https://github.com/tomasbruckner/jest-dotnet#configuring-serialization

**Describe alternatives you've considered**
Haven't yet

**Additional context**
N/A

**Comment by michaelstaib** [comment]
Thanks for your proposal. We will have a look at this.

**Comment by RohrerF** [comment]
In [v0.6.0](https://github.com/SwissLife-OSS/snapshooter/releases/tag/0.6.0) #117 is included which should make this possible.
