### ISSUE TITLE
Support for MsTest

### ISSUE THREAD

**Issue by sjwilczynski** [SwissLife-OSS/snapshooter#139]
Hey folks, does this library support MsTest framework. On the website I see that, support should come soon, but I am not sure if that information is up to date. If not are there any plans to do it?
![image](https://user-images.githubusercontent.com/19153565/134373680-470700aa-5ddd-423a-9418-11a6e6fe2e4b.png)

Thanks!

**Comment by nscheibe** [comment]
Hi, I will have a look this weekend if I can do it.

**Comment by aaronpowell** [comment]
Any chance of getting MSTest support? Happy to try and contribute it if that would be helpful.

**Comment by aaronpowell** [comment]
Woo! Let me know when there's a nuget package I can test against

**Comment by nscheibe** [comment]
Its released now (release 0.8.0)
