### ISSUE TITLE
How can I check that an array is not empty?

### ISSUE THREAD

**Issue by woeterman94** [SwissLife-OSS/snapshooter#140]
```
  {
    "number": 100000,
    "id": "017c3679-fb15-4720-a046-d88f50f07e39",
    "date": "0001-01-01T00:00:00.000Z",
    "version": "Version 1",
    "arrayWithIds": [
      "017c0902b9b441c0aeb273b376390830",
      "017c0902c1034c17a4ee696505cf67ce"
    ]
  }
```

How can I check that arrayWithIds is not empty?

I tried:

`.Assert(fieldOption => fieldOption.Field<Guid>("Data.myobject[*].arrayWithIds").Should().NotBeEmpty())
`
But that's giving me : **----> System.ArgumentException : Can not convert Array to Guid.**

I tried with

`.Assert(fieldOption => fieldOption.Field<Array>("Data.myobject[*].arrayWithIds").Should().NotBeEmpty())
`
But that's giving me:    **----> Newtonsoft.Json.JsonSerializationException : Could not create an instance of type System.Array.** 

Trying with the first element works` Data.myobject[*].arrayWithIds[0] `
but with `Data.myobject[*].arrayWithIds[*]` it returns an error as well:

`----> Snapshooter.Exceptions.SnapshotFieldException : The field of the path 'Data.myobject[*].arrayWithIds[*]' has an array as return value, Please use the FieldOption for fields array (Fields).`

**Comment by nscheibe** [comment]
Hi woeterman94, the path `Data.myobject[*].arrayWithIds[*]`  should be correct. Can you try the FieldOption with the property "Fields" instead of "Field", fieldOption.Fields("Data.myobject[*].arrayWithIds[*]"). 

I could not test it, therefore I am glad if you could tell me if it did work.

**Comment by woeterman94** [comment]
That works! I had to give a type to fields tho.

fieldOption.Fields<Guid>("Data.myobject[*].arrayWithIds[*]")

**Comment by nscheibe** [comment]
Perfect, I saw in the readme its Field instead of Fields, I corrected it in the readme.
