### ISSUE TITLE
WSL execution Support

### ISSUE THREAD

**Issue by joslat** [SwissLife-OSS/snapshooter#164]
**Is your feature request related to a problem? Please describe.**
WSL does not work and snapshot path/name cannot be determined.
I would like that so I can debug in local against a Linux machine in WSL/WSL2

**Describe the solution you'd like**
I want to be able to run my code that uses Snapshooter in WSL/WSL2

**Describe alternatives you've considered**

**Additional context**

**Comment by glucaci** [comment]
Hi @joslat can you post exactly the problem that you have?
We are running all the day our tests only on linux (ubuntu) agents and no problem at all.

Thanks!
