### ISSUE TITLE
Add Snapshooter icon to the Nuget package.

### ISSUE THREAD

**Issue by glucaci** [SwissLife-OSS/snapshooter#51]
Add Snapshooter icon to the Nuget package.

**Comment by RohrerF** [comment]
We need to change [this file](https://github.com/SwissLife-OSS/snapshooter/blob/master/src/Package.props) (property is commented out). But according to [this docu](https://github.com/NuGet/Home/wiki/Packaging-Icon-within-the-nupkg) we need to link a png/jpg. Currently we only have svg icons for snapshooter.

**Comment by glucaci** [comment]
Resolve by #54
