### ISSUE TITLE
Snapshot includes Subject of FluentAssertions

### ISSUE THREAD

**Issue by RohrerF** [SwissLife-OSS/snapshooter#56]
**Describe the bug**
If you use Snapshooter with FluentAssertions the snapshot includes properties which are not part of my object under test.

**To Reproduce**
1. Write a test like
```csharp
[Fact]
public void CreatePerson_VerifyPersonBySnapshot_SuccessfulVerified()
{
    // arrange
    var serviceClient = new ServiceClient();

    // act
    TestPerson person = serviceClient.CreatePerson("David", "Mustermann");

    // assert
    person.Should().MatchSnapshot();
}
```
2. Check the created snapshot
```
{
  "Subject": {
    "Firstname": "David",
    "Lastname": "Mustermann"
  }
}
```
3. realize that the snapshot includes the Subject Property of FluentAssertions.

**Expected behavior**
Snapshooter should remove this property("Subject") to make the snapshot look as if it was made without using FluentAssertions.
```
{
  "Firstname": "David",
  "Lastname": "Mustermann"
}
```

**Packageversions used:**
 - Snapshooter.Xunit 0.4.5

**Comment by michaelstaib** [comment]
Since when do we have this behavior?
