### ISSUE TITLE
Exclude from serialize process the ignore fields

### ISSUE THREAD

**Issue by glucaci** [SwissLife-OSS/snapshooter#59]
If we haven an object with ignored field e.g.:
```csharp
expected.MatchSnapshot(options => options.IgnoreField("Content"));
```
the field "Content" should not be serialized because may have a type which is not serializable.

**Comment by jannickj** [comment]
any movement on this?

**Comment by nscheibe** [comment]
My proposal is to create a new match option called .ExcludeField("Content"), which removes the specified field(s) from the snapshot. The IgnoreField is really only to ignore the field, but not change the snapshot output.
