### ISSUE TITLE
Version 0.5.0 not on Nuget

### ISSUE THREAD

**Issue by Foxliotelec** [SwissLife-OSS/snapshooter#63]
Hello

We use Snapshooter in our projects and we love it. The new strict mode is something we are very interested in. Although it was released on Github, I cannot find the version on Nuget. Am I missing something.

Greetings

**Comment by michaelstaib** [comment]
Yeah, I have to fix the build. Will do that tomorrow.

**Comment by Foxliotelec** [comment]
Okey great.

**Comment by michaelstaib** [comment]
@Foxliotelec I have fixed the build and the packages were just pushed to nuget.... they should become available in the next hour.

I am closing this issue.

**Comment by michaelstaib** [comment]
https://www.nuget.org/packages/Snapshooter/0.5.0

**Comment by Foxliotelec** [comment]
Thank you so much
