### ISSUE TITLE
match options are only applied at the 2nd time

### ISSUE THREAD

**Issue by bejto** [SwissLife-OSS/snapshooter#80]
match options are only applied at the 2nd time..

**Comment by nscheibe** [comment]
Yes we have to fix this! The 'assert' or 'typeof' match options are only applied if a snapshot already exists. The match options should fail already during the first execution.

**Comment by nscheibe** [comment]
A simple solution could be, that we compare during the first execution the original snapshot with itself, then all the match options would be applied...
