### ISSUE TITLE
Doesn't work with xunit TheoryAttribute tests

### ISSUE THREAD

**Issue by coderpatros** [SwissLife-OSS/snapshooter#81]
**Describe the bug**
Doesn't work with xunit TheoryAttribute tests

**To Reproduce**
Create a test like this...

```
        [Theory]
        [InlineData("a")]
        [InlineData("b")]
        [InlineData("c")]
        [InlineData("d")]
        public void DummyTest(string data)
        {
            Snapshot.Match(data);
        }
```

**Expected behavior**
A snapshot should be created for each variation of input data.

**Additional context**
This is a pretty tricky scenario to handle. The inline data could be pretty much anything.

**Comment by nscheibe** [comment]
We have in xUnit the issue, that we cannot get the Theory InlineData value of the actual running test.

Therefore we have a workaround for this scenario:
```
        [Theory]
        [InlineData("a")]
        [InlineData("b")]
        [InlineData("c")]
        [InlineData("d")]
        public void DummyTest(string data)
        {
            Snapshot.Match(data, SnapshotNameExtension.Create(data));
        }
```

**Comment by coderpatros** [comment]
Sounds like this is a case of RTFM :) 

Thanks @nscheibe
